/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.sysco.middleware.workshops.kafka.schema.issue.command;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CommandEnum {
  ADD  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CommandEnum\",\"namespace\":\"no.sysco.middleware.workshops.kafka.schema.issue.command\",\"symbols\":[\"ADD\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
