/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.sysco.middleware.workshops.kafka.schema.issue.event;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventEnum {
  ADDED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventEnum\",\"namespace\":\"no.sysco.middleware.workshops.kafka.schema.issue.event\",\"symbols\":[\"ADDED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
